-- 코드를 작성해주세요
SELECT ID, IFNULL(CHILD_COUNT,0)AS CHILD_COUNT FROM
(SELECT PARENT_ID,COUNT(PARENT_ID)AS CHILD_COUNT from ECOLI_DATA WHERE PARENT_ID IS NOT NULL GROUP BY PARENT_ID) AS TC RIGHT JOIN ECOLI_DATA ON ID = TC.PARENT_ID ORDER BY ID ASC